### PR TITLE
LBGG[Nuxt3]: Use `unplugin-icons`

### PR DESCRIPTION
**Pull request by erunks**
## What

Since our [old SVG icon library](https://www.npmjs.com/package/@nuxtjs/svg-sprite) doesn't support `Vue3`, and thus `Nuxt3` yet, in order to keep progress moving, I've implemented the use of [`unplugin-icons`](https://www.npmjs.com/package/unplugin-icons).

## Link to Issue

N/A

### Steps for testing

N/A

### Images
| Mobile | Tablet | Desktop |
| --- | --- | --- |
| mobile image | tablet image | desktop image

### CODE REVIEW

**Review by zysim — COMMENTED** [review]
I'd imagine that this is all that's needed to set icons up?

**Review by legrandgrand — APPROVED** [review]
Fix Ci and we will be good :)

**Comment by erunks** [comment]
> I'd imagine that this is all that's needed to set icons up?

Yeah, so the way this library works now isn't too different from before. We still can have all our custom SVGs in the `/assets/sprite/svg` directory, but instead of calling them like this `<svg-icon name="clock" />` we do it like this `<i-svg-clock />`

**Comment by zysim** [comment]
Lovely

**Review by buffet-time — APPROVED** [review]
Looks like good to me

**Pull request merged**
